version: '3'
services:
    mongodb:
        image: mongo:5.0.30
        restart: always
        volumes:
            - mongodata:/data/db

    pritunl:
        # Use the following to build the image from source (assuming you're running inside the repository).
        build:
            context: ../server
            dockerfile: ../docker/Dockerfile
            args:
                - API_SERVER_DOMAIN=${API_SERVER_DOMAIN:-}
        restart: always
        depends_on:
            - mongodb
        privileged: true
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        links:
            - mongodb
        volumes:
            - /etc/localtime:/etc/localtime:ro
        ports:
            # Under this port the Pritunl web interface will be exposed (for reverse proxies)
            - 9700:9700
            # The following are the two default ports for the tcp+udp servers (you may edit these as needed!)
            - 1194:1194
            - 1194:1194/udp
        environment:
            - TZ=UTC
            - MONGODB_URI=mongodb://mongodb:27017/pritunl
            # Also enable reverse proxie capabilities
            - REVERSE_PROXY=true
volumes:
    mongodata:
